#%RAML 1.0 NamedExample
[
        {
            "HREF": "https://{your_server}/api/v1/{your_account}/employees/10105",
            "BEGIN_OF_CONTRACT": "1997-09-21",
            "CELLULAR_NUMBER": "787-760-337",
            "DEPARTMENT_PATH": "DSI/Support",
            "DEPARTMENT_ID": "47",
            "E_MAIL": "lewis@evtry.com",
            "EMPLOYEE_ID": "10105",
            "LAST_NAME": "Lewis, Fabienne",
            "LOCATION_PATH": "Europe/France/Paris/Champs Elysées/111",
            "LOCATION_ID": "1530",
            "PHONE_NUMBER": "+33155859638",
            "LOCATION": {
                "HREF": "https://{your_server}/api/v1/{your_account}/locations/1530",
                "CITY": "",
                "LOCATION_CODE": "",
                "LOCATION_FR": "111",
                "LOCATION_PATH": "Europe/France/Paris/Champs Elysées/111",
                "LOCATION_ID": "1530"
            },
            "DEPARTMENT": {
                "HREF": "https://{your_server}/api/v1/{your_account}/departments/47",
                "DEPARTMENT_CODE": "",
                "DEPARTMENT_FR": "Support",
                "DEPARTMENT_PATH": "DSI/Support",
                "DEPARTMENT_ID": "47",
                "DEPARTMENT_LABEL": ""
            },
            "MANAGER": {
                "BEGIN_OF_CONTRACT": "",
                "CELLULAR_NUMBER": "",
                "DEPARTMENT_PATH": "",
                "E_MAIL": "",
                "EMPLOYEE_ID": "",
                "LAST_NAME": "",
                "LOCATION_PATH": "",
                "PHONE_NUMBER": ""
            }
        }]