#%RAML 1.0 Trait
responses:
  400:
      body:
        application/json:
          example: !include.. Example/400.json
  500:
         body:
          application/json:
            example: !include.. Example/500.json
  401:
         body:
          application/json:
            example: !include.. Example/401.json
  402:
        body:
          application/json:
            example: !include.. Example/402.json
  501:
         body:
          application/json:
              example: !include.. Example/501.json